name: hello-snap
base: core24
version: '0.1.0'
summary: Demo snap
description: Demo snap

grade: stable
confinement: strict

apps:
  hello-snap:
    command: hello.sh

parts:
  hello:
    source: .
    plugin: dump
