name: snap-lxc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@fix/refactor
    with:
      lxc-image: 'ubuntu:24.04'
      snap-test-script: |
        #!/bin/sh
        set -euxo pipefail
        hello-snap | grep "Hello World"
    secrets:
      snapstore-login: "secret"
